[[
  {
    "name": "mariadb.query",
    "service": "mariadb",
    "resource": "SELEC 1",
    "trace_id": 0,
    "span_id": 1,
    "parent_id": 0,
    "type": "sql",
    "error": 1,
    "meta": {
      "_dd.p.dm": "-0",
      "db.name": "test",
      "db.user": "test",
      "error.msg": "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'SELEC 1' at line 1",
      "error.stack": "Traceback (most recent call last):\n  File \"/root/project/ddtrace/contrib/dbapi/__init__.py\", line 81, in _trace_method\n    return method(*args, **kwargs)\n  File \"/root/project/.riot/venv_py3713_mariadb~10/lib/python3.7/site-packages/mariadb/cursors.py\", line 293, in execute\n    self._readresponse()\nmariadb.ProgrammingError: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SELEC 1' at line 1\n",
      "error.type": "mariadb.ProgrammingError",
      "out.host": "127.0.0.1",
      "runtime-id": "778c778962a54eeea3ae401d2417ef86"
    },
    "metrics": {
      "_dd.agent_psr": 1.0,
      "_dd.measured": 1,
      "_dd.top_level": 1,
      "_dd.tracer_kr": 1.0,
      "_sampling_priority_v1": 1,
      "db.rowcount": -1,
      "out.port": 3306,
      "system.pid": 9677
    },
    "duration": 4552500,
    "start": 1656521264312730600
  }]]
